apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      mi-app: hello
  template:
    metadata:
      labels:
        mi-app: hello
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              mi-app: hello
      containers:
        - name: hello-from
          image: 'pbitty/hello-from:latest'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80

